name: SudoVersity
avatar: images/sudoversity.webp # Avatar image. Default to "images/profile.webp".
bio: "Knowledge Shared. Ideas Explored."
#company: Love Sudo # HTML markup are supported, such as: <a href="https://example.com" target="_blank" rel="noopener noreferrer">Company</a>.
location: United Kingdom # HTML markup are supported, such as: <a href='https://www.openstreetmap.org/search?query=Earth'>Earth</a>.
# about: https://razonyang.com # The external about page. The internal about page will be used if not set.
#params:
#  layout: compact
# See https://hbs.razonyang.com/v1/en/docs/widgets/social-links/.
social:
  email: josey@lovesudo.com
  github: sudomistress
  mastodon: josey@mastodon.aspectsof.love
  rss: "" # Remove RSS
